[colors]
primary.background = '#1d2021'
primary.foreground = '#ebdbb2'

[colors.normal]
black   = '#1d2021'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[colors.bright]
black   = '#3c3836'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#f2e5bc'

[colors.cursor]
text = '#282828'
cursor = '#d65d0e'

